import 'bootstrap/dist/css/bootstrap.css';
import '@/styles/clean-blog.css';
import 'font-awesome/css/font-awesome.css';
import Head from 'next/head';
import { useEffect } from 'react';
import Footer from '@/components/Layout/Footer';
import Navigation from '@/components/Layout/Navigation';

export default function App({ Component, pageProps }) {
  useEffect(() => {
    import('jquery').then((jquery) => {
      window.$ = jquery.default;
      window.jQuery = jquery.default;
      import('bootstrap/dist/js/bootstrap.min.js');
    });
  }, []);
  return (
    <>
      <Head>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navigation />
      <Component {...pageProps} />
      <hr />
      <Footer />
    </>
  );
}
